/* User Login action types */

//AUTH ACTIONS
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
//TODO: Add LOGOUT_USER Action

//USER ACTIONS
export const FETCH_ALL_USERS_REQUEST = "FETCH_ALL_USERS_REQUEST";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILURE = "FETCH_ALL_USERS_FAILURE";

export const CREATE_NEW_USER_REQUEST = "CREATE_NEW_USER_REQUEST";
export const CREATE_NEW_USER_SUCCESS = "CREATE_NEW_USER_SUCCESS";
export const CREATE_NEW_USER_FAILURE = "CREATE_NEW_USER_FAILURE";

export const UPDATE_USER_DATA_REQUEST = "UPDATE_USER_DATA_REQUEST";
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAILURE = "UPDATE_USER_DATA_FAILURE";

export const DELETE_USER_DATA_REQUEST = "DELETE_USER_DATA_REQUEST";
export const DELETE_USER_DATA_SUCCESS = "DELETE_USER_DATA_SUCCESS";
export const DELETE_USER_DATA_FAILURE = "DELETE_USER_DATA_FAILURE";

//COUNTRY ACTIONS
export const FETCH_ALL_COUNTRIES_REQUEST = "FETCH_ALL_COUNTRIES_REQUEST";
export const FETCH_ALL_COUNTRIES_SUCCESS = "FETCH_ALL_COUNTRIES_SUCCESS";
export const FETCH_ALL_COUNTRIES_FAILURE = "FETCH_ALL_COUNTRIES_FAILURE";
export const LOAD_ALL_EXT_COUNTRIES_REQUEST = "LOAD_ALL_EXT_COUNTRIES_REQUEST";
export const LOAD_ALL_EXT_COUNTRIES_SUCCESS = "LOAD_ALL_EXT_COUNTRIES_SUCCESS";
export const LOAD_ALL_EXT_COUNTRIES_FAILURE = "LOAD_ALL_EXT_COUNTRIES_FAILURE";

export const ADD_COUNTRY_REQUEST = "ADD_COUNTRY_REQUEST";
export const ADD_COUNTRY_SUCCESS = "ADD_COUNTRY_SUCCESS";
export const ADD_COUNTRY_FAILURE = "ADD_COUNTRY_FAILURE";

export const UPDATE_COUNTRY_REQUEST = "UPDATE_COUNTRY_REQUEST";
export const UPDATE_COUNTRY_SUCCESS = "UPDATE_COUNTRY_SUCCESS";
export const UPDATE_COUNTRY_FAILURE = "UPDATE_COUNTRY_FAILURE";

export const DELETE_COUNTRY_REQUEST = "DELETE_COUNTRY_REQUEST";
export const DELETE_COUNTRY_SUCCESS = "DELETE_COUNTRY_SUCCESS";
export const DELETE_COUNTRY_FAILURE = "DELETE_COUNTRY_FAILURE";

export const FETCH_COUNTRY_TOWN_REQUEST = "FETCH_COUNTRY_TOWN_REQUEST";
export const FETCH_COUNTRY_TOWN_SUCCESS = "FETCH_COUNTRY_TOWN_SUCCESS";
export const FETCH_COUNTRY_TOWN_FAILURE = "FETCH_COUNTRY_TOWN_FAILURE";

//TOWN ACTIONS
export const FETCH_TOWNS_REQUEST = "FETCH_TOWNS_REQUEST";
export const FETCH_TOWNS_SUCCESS = "FETCH_TOWNS_SUCCESS";
export const FETCH_TOWNS_FAILURE = "FETCH_TOWNS_FAILURE";

export const ADD_TOWN_REQUEST = "ADD_TOWN_REQUEST";
export const ADD_TOWN_SUCCESS = "ADD_TOWN_SUCCESS";
export const ADD_TOWN_FAILURE = "ADD_TOWN_FAILURE";

export const UPDATE_TOWN_REQUEST = "UPDATE_TOWN_REQUEST";
export const UPDATE_TOWN_SUCCESS = "UPDATE_TOWN_SUCCESS";
export const UPDATE_TOWN_FAILURE = "UPDATE_TOWN_FAILURE";

export const DELETE_TOWN_REQUEST = "DELETE_TOWN_REQUEST";
export const DELETE_TOWN_SUCCESS = "DELETE_TOWN_SUCCESS";
export const DELETE_TOWN_FAILURE = "DELETE_TOWN_FAILURE";

//PICKUP ACTIONS
export const FETCH_PICKUP_AREAS_REQUEST = "FETCH_PICKUP_AREAS_REQUEST";
export const FETCH_PICKUP_AREAS_SUCCESS = "FETCH_PICKUP_AREAS_SUCCESS";
export const FETCH_PICKUP_AREAS_FAILURE = "FETCH_PICKUP_AREAS_FAILURE";

export const ADD_PICKUP_AREA_REQUEST = "ADD_PICKUP_AREA_REQUEST";
export const ADD_PICKUP_AREA_SUCCESS = "ADD_PICKUP_AREA_SUCCESS";
export const ADD_PICKUP_AREA_FAILURE = "ADD_PICKUP_AREA_FAILURE";

export const UPDATE_PICKUP_AREA_REQUEST = "UPDATE_PICKUP_AREA_REQUEST";
export const UPDATE_PICKUP_AREA_SUCCESS = "UPDATE_PICKUP_AREA_SUCCESS";
export const UPDATE_PICKUP_AREA_FAILURE = "UPDATE_PICKUP_AREA_FAILURE";

export const DELETE_PICKUP_AREA_REQUEST = "DELETE_PICKUP_AREA_REQUEST";
export const DELETE_PICKUP_AREA_SUCCESS = "DELETE_PICKUP_AREA_SUCCESS";
export const DELETE_PICKUP_AREA_FAILURE = "DELETE_PICKUP_AREA_FAILURE";

//DRIVER ACTIONS
export const FETCH_DRIVER_REQUEST = "FETCH_DRIVER_REQUEST";
export const FETCH_DRIVER_SUCCESS = "FETCH_DRIVER_SUCCESS";
export const FETCH_DRIVERS_FAILURE = "FETCH_DRIVER_FAILURE";

export const ADD_DRIVER_REQUEST = "ADD_DRIVER_REQUEST";
export const ADD_DRIVER_SUCCESS = "ADD_DRIVER_SUCCESS";
export const ADD_DRIVER_FAILURE = "ADD_DRIVER_FAILURE";

export const UPDATE_DRIVER_REQUEST = "UPDATE_DRIVER_REQUEST";
export const UPDATE_DRIVER_SUCCESS = "UPDATE_DRIVER_SUCCESS";
export const UPDATE_DRIVER_FAILURE = "UPDATE_DRIVER_FAILURE";

export const DELETE_DRIVER_REQUEST = "DELETE_DRIVER_REQUEST";
export const DELETE_DRIVER_SUCCESS = "DELETE_DRIVER_SUCCESS";
export const DELETE_DRIVER_FAILURE = "DELETE_DRIVER_FAILURE";

// TAXI ACTIONS
export const ADD_TAXI_REQUEST = "ADD_TAXI_REQUEST";
export const ADD_TAXI_SUCCESS = "ADD_TAXI_SUCCESS";
export const ADD_TAXI_FAILURE = "ADD_TAXI_FAILURE";

export const FETCH_TAXI_REQUEST = "FETCH_TAXI_REQUEST";
export const FETCH_TAXI_SUCCESS = "FETCH_TAXI_SUCCESS";
export const FETCH_TAXI_FAILURE = "FETCH_TAXI_FAILURE";

export const UPDATE_TAXI_REQUEST = "UPDATE_TAXI_REQUEST";
export const UPDATE_TAXI_SUCCESS = "UPDATE_TAXI_SUCCESS";
export const UPDATE_TAXI_FAILURE = "UPDATE_TAXI_FAILURE";

export const DELETE_TAXI_REQUEST = "DELETE_TAXI_REQUEST";
export const DELETE_TAXI_SUCCESS = "DELETE_TAXI_SUCCESS";
export const DELETE_TAXI_FAILURE = "DELETE_TAXI_FAILURE";

// TAXI_DRIVERS
export const ASSIGN_TAXI_DRIVER_REQUEST = "ASSIGN_TAXI_DRIVER_REQUEST";
export const ASSIGN_TAXI_DRIVER_SUCCESS = "ASSIGN_TAXI_DRIVER_SUCCESS";
export const ASSIGN_TAXI_DRIVER_FAILURE = "ASSIGN_TAXI_DRIVER_FAILURE";

export const FETCH_TAXI_DRIVER_REQUEST = "FETCH_TAXI_DRIVER_REQUEST";
export const FETCH_TAXI_DRIVER_SUCCESS = "FETCH_TAXI_DRIVER_SUCCESS";
export const FETCH_TAXI_DRIVER_FAILURE = "FETCH_TAXI_DRIVER_FAILURE";

export const UPDATE_TAXI_DRIVER_REQUEST = "UPDATE_TAXI_DRIVER_REQUEST";
export const UPDATE_TAXI_DRIVER_SUCCESS = "UPDATE_TAXI_DRIVER_SUCCESS";
export const UPDATE_TAXI_DRIVER_FAILURE = "UPDATE_TAXI_DRIVER_FAILURE";

export const DELETE_TAXI_DRIVER_REQUEST = "DELETE_TAXI_DRIVER_REQUEST";
export const DELETE_TAXI_DRIVER_SUCCESS = "DELETE_TAXI_DRIVER_SUCCESS";
export const DELETE_TAXI_DRIVER_FAILURE = "DELETE_TAXI_DRIVER_FAILURE";

// DRIVER APPLICATION
export const FETCH_DRIVER_APP_REQUEST = "FETCH_DRIVER_APP_REQUEST";
export const FETCH_DRIVER_APP_SUCCESS = "FETCH_DRIVER_APP_SUCCESS";
export const FETCH_DRIVER_APP_FAILURE = "FETCH_DRIVER_APP_FAILURE";

// SUBSCRIPTION PLAN
export const FETCH_SUBSCRIPTION_PLAN_REQUEST =
  "FETCH_SUBSCRIPTION_PLAN_REQUEST";
export const FETCH_SUBSCRIPTION_PLAN_SUCCESS =
  "FETCH_SUBSCRIPTION_PLAN_SUCCESS";
export const FETCH_SUBSCRIPTION_PLAN_FAILURE =
  "FETCH_SUBSCRIPTION_PLAN_FAILURE";

export const ADD_SUBSCRIPTION_PLAN_REQUEST = "ADD_SUBSCRIPTION_PLAN_REQUEST";
export const ADD_SUBSCRIPTION_PLAN_SUCCESS = "ADD_SUBSCRIPTION_PLAN_SUCSESS";
export const ADD_SUBSCRIPTION_PLAN_FAILURE = "ADD_SUBSCRIPTION_PLAN_FAILURE";

export const UPDATE_SUBSCRIPTION_PLAN_REQUEST =
  "UPDATE_SUBSCRIPTION_PLAN_REQUEST";
export const UPDATE_SUBSCRIPTION_PLAN_SUCCESS =
  "UPDATE_SUBSCRIPTION_PLAN_SUCCESS";
export const UPDATE_SUBSCRIPTION_PLAN_FAILURE =
  "UPDATE_SUBSCRIPTION_PLAN_FAILURE";

export const DELETE_SUBSCRIPTION_PLAN_REQUEST =
  "DELETE_SUBSCRIPTION_PLAN_REQUEST";
export const DELETE_SUBSCRIPTION_PLAN_SUCCESS =
  "DELETE_SUBSCRIPTION_PLAN_SUCCESS";
export const DELETE_SUBSCRIPTION_PLAN_FAILURE =
  "DELETE_SUBSCRIPTION_PLAN_FAILURE";

// PRICES MANAGEMENT
export const ADD_PRICE_REAUEST = "ADD_PRICE_REAUEST";
export const ADD_PRICE_SUCCESS = "ADD_PRICE_SUCCESS";
export const ADD_PRICE_FAILURE = "ADD_PRICE_FAILURE";

export const UPDATE_PRICE_REQUEST = "UPDATE_PRICE_REQUEST";
export const UPDATE_PRICE_SUCCESS = "UPDATE_PRICE_SUCCESS";
export const UPDATE_PRICE_FAILURE = "UPDATE_PRICE_FAILURE";

export const FETCH_PRICE_REQUEST = "FETCH_PRICE_REQUEST";
export const FETCH_PRICE_SUCCESS = "FETCH_PRICE_SUCCESS";
export const FETCH_PRICE_FAILURE = "FETCH_PRICE_FAILURE";

export const DELETE_PRICE_REQUEST = "DELETE_PRICE_REQUEST";
export const DELETE_PRICE_SUCCESS = "DELETE_PRICE_SUCCESS";
export const DELETE_PRICE_FAILURE = "DELETE_PRICE_FAILURE";

// CLIENTS

export const FETCH_CLIENT_REQUEST =
  "FETCH_CLIENT_REQUEST";
export const FETCH_CLIENT_SUCCESS =
  "FETCH_CLIENT_SUCCESS";
export const FETCH_CLIENT_FAILURE =
  "FETCH_CLIENT_FAILURE";


export const FETCH_REQUEST =
  "FETCH_REQUEST";
export const FETCH_REQUEST_SUCCESS =
  "FETCH_REQUEST_SUCCESS";
export const FETCH_REQUEST_FAILURE =
  "FETCH_REQUEST_FAILURE";

// export const ADD_CLIENT_REQUEST = "ADD_CLIENT_REQUEST";
// export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCSESS";
// export const ADD_CLIENT_FAILURE = "ADD_CLIENT_FAILURE";

// export const UPDATE_CLIENT_REQUEST =
//   "UPDATE_CLIENT_REQUEST";
// export const UPDATE_CLIENT_SUCCESS =
//   "UPDATE_CLIENT_SUCCESS";
// export const UPDATE_CLIENT_FAILURE =
//   "UPDATE_CLIENT_FAILURE";

// export const DELETE_CLIENT_REQUEST =
//   "DELETE_CLIENT_REQUEST";
// export const DELETE_CLIENT_SUCCESS =
//   "DELETE_CLIENT_SUCCESS";
// export const DELETE_CLIENT_FAILURE =
//   "DELETE_CLIENT_FAILURE";